//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalaGroupERPEntities : DbContext
    {
        public MalaGroupERPEntities()
            : base("name=MalaGroupERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<syNavigationNode> syNavigationNodes { get; set; }
        public virtual DbSet<syResource> syResources { get; set; }
        public virtual DbSet<syResourceType> syResourceTypes { get; set; }
        public virtual DbSet<syRoleResource> syRoleResources { get; set; }
        public virtual DbSet<syRole> syRoles { get; set; }
        public virtual DbSet<syRolesResourcesLevel> syRolesResourcesLevels { get; set; }
        public virtual DbSet<syUsersRole> syUsersRoles { get; set; }
        public virtual DbSet<tblLoginHistory> tblLoginHistories { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblPagesLoginHistory> tblPagesLoginHistories { get; set; }
        public virtual DbSet<tbl_VehicleType> tbl_VehicleType { get; set; }
        public virtual DbSet<tbl_Question> tbl_Question { get; set; }
        public virtual DbSet<tbl_VehicleLeads> tbl_VehicleLeads { get; set; }
        public virtual DbSet<tbl_AgentOrder> tbl_AgentOrder { get; set; }
        public virtual DbSet<tbl_CallHistory> tbl_CallHistory { get; set; }
        public virtual DbSet<tbl_NotExportLead> tbl_NotExportLead { get; set; }
        public virtual DbSet<tbl_Calls> tbl_Calls { get; set; }
        public virtual DbSet<tbl_Events> tbl_Events { get; set; }
        public virtual DbSet<tbl_Tasks> tbl_Tasks { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tbl_AttachedFiles> tbl_AttachedFiles { get; set; }
        public virtual DbSet<tbl_FromAddress> tbl_FromAddress { get; set; }
        public virtual DbSet<tbl_VehicleAO> tbl_VehicleAO { get; set; }
        public virtual DbSet<tbl_ABSCreditCrad> tbl_ABSCreditCrad { get; set; }
        public virtual DbSet<tbl_Notes> tbl_Notes { get; set; }
        public virtual DbSet<tbl_ViewedBy> tbl_ViewedBy { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<tbl_ChatViewedBy> tbl_ChatViewedBy { get; set; }
        public virtual DbSet<tbl_LeadInformation> tbl_LeadInformation { get; set; }
        public virtual DbSet<tbl_EmailTemplates> tbl_EmailTemplates { get; set; }
        public virtual DbSet<tbl_ExportHistory> tbl_ExportHistory { get; set; }
        public virtual DbSet<tbl_Chattter> tbl_Chattter { get; set; }
        public virtual DbSet<tbl_Accounts> tbl_Accounts { get; set; }
        public virtual DbSet<tbl_AuditTrail> tbl_AuditTrail { get; set; }
        public virtual DbSet<tbl_OrderCardCheckInfo> tbl_OrderCardCheckInfo { get; set; }
        public virtual DbSet<tbl_Package> tbl_Package { get; set; }
        public virtual DbSet<tbl_AOScript> tbl_AOScript { get; set; }
        public virtual DbSet<tbl_ReportTakeOffListCriteria> tbl_ReportTakeOffListCriteria { get; set; }
        public virtual DbSet<tbl_EMails> tbl_EMails { get; set; }
        public virtual DbSet<tbl_Snippet> tbl_Snippet { get; set; }
        public virtual DbSet<tbl_CustomReportDataType> tbl_CustomReportDataType { get; set; }
        public virtual DbSet<tbl_CustomReportFields> tbl_CustomReportFields { get; set; }
        public virtual DbSet<tbl_CustomReportFilters> tbl_CustomReportFilters { get; set; }
        public virtual DbSet<tbl_ReportTables> tbl_ReportTables { get; set; }
        public virtual DbSet<tbl_ReportTablesFields> tbl_ReportTablesFields { get; set; }
        public virtual DbSet<tbl_ReportTablesJoins> tbl_ReportTablesJoins { get; set; }
        public virtual DbSet<tbl_CustomReport> tbl_CustomReport { get; set; }
        public virtual DbSet<tbl_AgentOrderDetails> tbl_AgentOrderDetails { get; set; }
        public virtual DbSet<tbl_AccountOwner> tbl_AccountOwner { get; set; }
        public virtual DbSet<tbl_VehicleMake> tbl_VehicleMake { get; set; }
        public virtual DbSet<tbl_OrderTransactions> tbl_OrderTransactions { get; set; }
    }
}
