//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class syRole
    {
        public syRole()
        {
            this.syRoleResources = new HashSet<syRoleResource>();
            this.syRolesResourcesLevels = new HashSet<syRolesResourcesLevel>();
            this.syUsersRoles = new HashSet<syUsersRole>();
        }
    
        public int RoleId { get; set; }
        public string RoleCode { get; set; }
        public string RoleDescription { get; set; }
        public bool RoleStatus { get; set; }
    
        public virtual ICollection<syRoleResource> syRoleResources { get; set; }
        public virtual ICollection<syRolesResourcesLevel> syRolesResourcesLevels { get; set; }
        public virtual ICollection<syUsersRole> syUsersRoles { get; set; }
    }
}
