//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class syRolesResourcesLevel
    {
        public int RRLId { get; set; }
        public int RoleId { get; set; }
        public int ModuleId { get; set; }
        public int ResourceId { get; set; }
        public int AccessLevel { get; set; }
        public int HasSpecialRight { get; set; }
    
        public virtual syRole syRole { get; set; }
    }
}
