//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExportHistory
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> DuplicateCount { get; set; }
        public Nullable<System.DateTime> DateExported { get; set; }
        public Nullable<int> IsExported { get; set; }
        public Nullable<int> IsViewed { get; set; }
    }
}
