//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NotExportLead
    {
        public long ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string VIN { get; set; }
        public string YEAR { get; set; }
        public string MAKE { get; set; }
        public string VEHTYPE { get; set; }
        public string LOGIN { get; set; }
        public string EXPIRATIONDATE { get; set; }
        public string PASSWORD { get; set; }
        public string LISTCODE { get; set; }
        public string LENDER_NAME { get; set; }
        public string LOAD_DATE { get; set; }
        public string DEALERSHIP { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
    }
}
