//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Accounts
    {
        public long ID { get; set; }
        public string AccountName { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> AccountOwner { get; set; }
        public Nullable<int> ParentAccount { get; set; }
        public Nullable<int> Industry { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Description { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public Nullable<long> LeadID { get; set; }
        public string Password { get; set; }
        public Nullable<long> AOID { get; set; }
        public string PinNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<int> PersonContactId { get; set; }
        public int IsDeleted { get; set; }
        public string CustomerProfileID { get; set; }
        public string CustomerPaymentID { get; set; }
        public string CustomerAddressID { get; set; }
        public string EmailId { get; set; }
        public string RecordTypeId { get; set; }
        public Nullable<System.DateTime> AccountCancellationDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
    }
}
