//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderCardCheckInfo
    {
        public long CCID { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string CardSecurityCode { get; set; }
        public string CheckNo { get; set; }
        public Nullable<long> AOID { get; set; }
        public Nullable<long> LeadID { get; set; }
        public string CardName { get; set; }
        public Nullable<int> IsDefault { get; set; }
    }
}
