//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notes
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> NotesDate { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> LastModifiedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
