//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public long TransactionID { get; set; }
        public string CardDetail { get; set; }
        public Nullable<int> CardType { get; set; }
        public string CardNumber { get; set; }
        public string Token { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string CardSecurityCode { get; set; }
        public Nullable<long> AOID { get; set; }
        public Nullable<long> LeadID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> AccountID { get; set; }
    }
}
