//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EMails
    {
        public long ID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<long> AutoGenID { get; set; }
        public string FromEmail { get; set; }
        public string ToEmails { get; set; }
        public string CCEmails { get; set; }
        public string BCCEmails { get; set; }
        public string EmailSubject { get; set; }
        public string EmailHTMLBody { get; set; }
        public string EmailPlainText { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AttachedFileName { get; set; }
        public string OriginalFileName { get; set; }
    }
}
