//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VehicleAO
    {
        public long ID { get; set; }
        public Nullable<int> VehicleMake { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string VehicleYear { get; set; }
        public string VINNo { get; set; }
        public string LicensePlate { get; set; }
        public string Dealership { get; set; }
        public string FinanceCompany { get; set; }
        public long AOID { get; set; }
    }
}
