//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AgentOrderDetails
    {
        public long AODID { get; set; }
        public Nullable<long> AOID { get; set; }
        public Nullable<int> VehicleMake { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string VehicleYear { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string AdditionalPackage { get; set; }
        public Nullable<int> IsDiffBillingAdd { get; set; }
        public string BStreet { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BZipCode { get; set; }
        public Nullable<System.DateTime> FirstChargeDate { get; set; }
        public Nullable<int> ChargeDay { get; set; }
        public Nullable<int> NoOfVehicle { get; set; }
        public Nullable<int> AddDecals { get; set; }
        public Nullable<int> IdentityTheft { get; set; }
        public string TotalAmt { get; set; }
        public Nullable<decimal> PackageAmt { get; set; }
        public string AdditionalPackageAmt { get; set; }
        public string DecalNumber1 { get; set; }
        public string DecalNumber2 { get; set; }
        public string DecalNumber3 { get; set; }
        public string DecalNumber4 { get; set; }
        public string GPSSKU1 { get; set; }
        public string GPSSKU2 { get; set; }
        public string GPSSKU3 { get; set; }
        public string GPSSKU4 { get; set; }
        public string GPSDN1 { get; set; }
        public string GPSDN2 { get; set; }
        public string GPSDN3 { get; set; }
        public string GPSDN4 { get; set; }
        public string VINNo { get; set; }
        public string LicensePlate { get; set; }
        public string Dealership { get; set; }
        public string FinanceCompany { get; set; }
        public string Warranty { get; set; }
        public Nullable<int> VehicleMake2 { get; set; }
        public Nullable<int> VehicleMake3 { get; set; }
        public Nullable<int> VehicleMake4 { get; set; }
        public string VehicleYear2 { get; set; }
        public string VehicleYear3 { get; set; }
        public string VehicleYear4 { get; set; }
        public string VINNo2 { get; set; }
        public string VINNo3 { get; set; }
        public string VINNo4 { get; set; }
        public string LicensePlate2 { get; set; }
        public string LicensePlate3 { get; set; }
        public string LicensePlate4 { get; set; }
        public Nullable<int> CompType { get; set; }
        public Nullable<int> TooMuch { get; set; }
    }
}
