//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditTrail
    {
        public long ATID { get; set; }
        public string AuditDetails { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<long> AGID { get; set; }
    }
}
