//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportTakeOffListCriteria
    {
        public long ReportID { get; set; }
        public Nullable<System.DateTime> LastModifiedFrom { get; set; }
        public Nullable<System.DateTime> LastModifiedTo { get; set; }
        public Nullable<int> IsTakeOFF { get; set; }
        public Nullable<int> Show { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<int> ReportStatus { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
