//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomReport
    {
        public long ID { get; set; }
        public Nullable<long> TableID { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> CreatdedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedtedBY { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public Nullable<int> IsSaved { get; set; }
    }
}
