//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AOScript
    {
        public int AOSID { get; set; }
        public string AOScript { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Step { get; set; }
    }
}
