//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Package
    {
        public int PackageID { get; set; }
        public string Package { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<int> Additional { get; set; }
        public Nullable<int> AddDecal { get; set; }
        public Nullable<int> AddIdentityTheft { get; set; }
        public Nullable<int> DecalNumber { get; set; }
        public Nullable<int> IsRenewal { get; set; }
    }
}
