//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderTransactions
    {
        public long CDID { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<long> AOID { get; set; }
        public Nullable<int> ChargeNo { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string TransactionID { get; set; }
        public string AuthCode { get; set; }
        public string TransHashCode { get; set; }
        public string CardCheckNumber { get; set; }
        public string CardType { get; set; }
        public Nullable<decimal> ChargeAmt { get; set; }
        public Nullable<int> Status { get; set; }
        public string SubscriptionID { get; set; }
        public Nullable<decimal> RefundAmt { get; set; }
        public string GatewayID { get; set; }
        public string GatwayResponse { get; set; }
        public string ResonText { get; set; }
        public string StatusText { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> MailSend { get; set; }
    }
}
