//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeadInformation
    {
        public long LeadID { get; set; }
        public Nullable<int> LeadStatus { get; set; }
        public Nullable<int> LeadOwner { get; set; }
        public string Name { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string LeadEmail { get; set; }
        public string ListCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Warranty { get; set; }
        public string Language { get; set; }
        public string ListCode2 { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Password { get; set; }
        public string PinNo { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> IsConverted { get; set; }
        public string LastModifiedById { get; set; }
        public string OwnerIDText { get; set; }
        public Nullable<System.DateTime> ConvertedDate { get; set; }
        public string AccountText { get; set; }
        public string Password_Generator__c { get; set; }
        public Nullable<int> AOStatus { get; set; }
        public Nullable<int> Take_Off_List__c { get; set; }
        public string VechileMake { get; set; }
        public string VechileTye { get; set; }
        public string VechileYear { get; set; }
        public string DelearShip { get; set; }
        public string Finance { get; set; }
        public string VinNo { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
