//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int MessageId { get; set; }
        public Nullable<int> MessageFrom { get; set; }
        public Nullable<int> MessageTo { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageTime { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
