//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaGroupERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagesLoginHistory
    {
        public long PHID { get; set; }
        public Nullable<long> LHID { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> PageInDateTime { get; set; }
        public Nullable<System.DateTime> PageOutDateTime { get; set; }
    }
}
